//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblImportOrder()
        {
            this.tblCheckinDetails = new HashSet<tblCheckinDetail>();
            this.tblImportMaterials = new HashSet<tblImportMaterial>();
        }
    
        public int PK_iImportOrderID { get; set; }
        public int FK_iAccountID { get; set; }
        public int FK_iSupplierID { get; set; }
        public Nullable<System.DateTime> dtDateAdded { get; set; }
        public string sDeliver { get; set; }
        public Nullable<int> iState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckinDetail> tblCheckinDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImportMaterial> tblImportMaterials { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
