//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaterPriceImport
    {
        public int PK_iMaterPriceImportID { get; set; }
        public int FK_iMaterialID { get; set; }
        public Nullable<double> fMaterPriceImport { get; set; }
        public Nullable<System.DateTime> dtStartDay { get; set; }
        public Nullable<System.DateTime> dtEndDay { get; set; }
    
        public virtual tblMaterial tblMaterial { get; set; }
    }
}
