//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblCheckoutDetails = new HashSet<tblCheckoutDetail>();
        }
    
        public int PK_iOrderID { get; set; }
        public int FK_iAccountID { get; set; }
        public string sCustomerName { get; set; }
        public string sCustomerPhone { get; set; }
        public string sDeliveryAddress { get; set; }
        public System.DateTime dInvoidDate { get; set; }
        public string sBiller { get; set; }
        public Nullable<int> iDeliveryMethod { get; set; }
        public Nullable<double> fSurcharge { get; set; }
        public Nullable<int> iPaid { get; set; }
        public string sState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckoutDetail> tblCheckoutDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
