//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductColor
    {
        public int PK_iProductColorID { get; set; }
        public int FK_iProductID { get; set; }
        public string sProductColor { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
